# Generated by Django 4.2.25 on 2026-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
