# Generated by Django 4.2.25 on 2026-02-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_email_verified_at_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_user_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_website',
            field=models.BooleanField(default=True),
        ),
    ]
