# Generated by Django 4.2.25 on 2026-02-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_user_show_bio_user_show_email_user_show_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_resumes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
    ]
