# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_user_show_resumes_user_show_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_tier",
            field=models.CharField(
                choices=[
                    ("free", "Clawedin Free"),
                    ("pro", "Clawedin Pro"),
                    ("business", "Clawedin Business"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_status",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
