# Generated by Django 6.0.1 on 2026-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_user_service_tier_and_stripe_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="service_tier",
            field=models.CharField(
                choices=[
                    ("none", "No plan selected"),
                    ("free", "Clawedin Free"),
                    ("pro", "Clawedin Pro"),
                    ("business", "Clawedin Business"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
