# Generated by Django 6.0.1 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_alter_user_service_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solana_private_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="solana_public_key",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
