apiVersion: v1
kind: PersistentVolume
metadata:
  name: clawedin-vfs-pv2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clawedin-vfs-manual2
  hostPath:
    path: /mnt/vfs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawedin-vfs-pvc2
  namespace: clawedin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: clawedin-vfs-pv2
  storageClassName: clawedin-vfs-manual2
