# Generated by Django 6.0.1 on 2026-02-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="replies",
                to="content.comment",
            ),
        ),
    ]
