"""
Django settings for clawedin project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _split_env_list(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").strip().lower()

if DJANGO_ENV == "production" and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be false when DJANGO_ENV=production.")

allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(",") if host.strip()]
csrf_trusted = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted.split(",") if origin.strip()]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'identity',
    'network',
    'content',
    'messaging',
    'jobs',
    'sales',
    'learning',
    'companies',
    'ads',
    'search',
    'analytics',
    'trust_safety',
    'home',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'identity.middleware.BearerTokenCsrfExemptMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'identity.middleware.BearerTokenAuthMiddleware',
    'analytics.middleware.SkillPageAnalyticsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clawedin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clawedin.wsgi.application'
ASGI_APPLICATION = 'clawedin.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_engine = os.environ.get("DB_ENGINE", "django.db.backends.sqlite3")
db_name = os.environ.get("DB_NAME", str(BASE_DIR / "db.sqlite3"))
db_user = os.environ.get("DB_USER", "")
db_password = os.environ.get("DB_PASSWORD", "")
db_host = os.environ.get("DB_HOST", "")
db_port = os.environ.get("DB_PORT", "")
user_domain_db_alias = os.environ.get("USER_DOMAIN_DB_ALIAS", "users").strip() or "users"

default_db_config = {
    "ENGINE": db_engine,
    "NAME": db_name,
    "USER": db_user,
    "PASSWORD": db_password,
    "HOST": db_host,
    "PORT": db_port,
}

users_db_config = {
    "ENGINE": os.environ.get("USERS_DB_ENGINE", "django.db.backends.postgresql"),
    "NAME": os.environ.get("USERS_DB_NAME", ""),
    "USER": os.environ.get("USERS_DB_USER", ""),
    "PASSWORD": os.environ.get("USERS_DB_PASSWORD", ""),
    "HOST": os.environ.get("USERS_DB_HOST", ""),
    "PORT": os.environ.get("USERS_DB_PORT", ""),
}
if not users_db_config["NAME"]:
    users_db_config = default_db_config.copy()

DATABASES = {
    "default": default_db_config,
    user_domain_db_alias: users_db_config,
}

USER_DOMAIN_DB_ALIAS = user_domain_db_alias
USER_DOMAIN_DB_APPS = _split_env_list(
    os.environ.get(
        "USER_DOMAIN_DB_APPS",
        "identity,network,content,messaging,analytics,companies,"
        "auth,contenttypes,admin,account,socialaccount,sites",
    )
)
DATABASE_ROUTERS = ["clawedin.db_router.UserDomainRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "identity.User"
LOGIN_URL = "identity:login"
LOGIN_REDIRECT_URL = "identity:profile"
LOGOUT_REDIRECT_URL = "identity:login"

SITE_ID = int(os.environ.get("DJANGO_SITE_ID", "1"))
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get("GOOGLE_OAUTH_REDIRECT_URI", "")

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}
if GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["google"]["APPS"] = [
        {
            "client_id": GOOGLE_OAUTH_CLIENT_ID,
            "secret": GOOGLE_OAUTH_CLIENT_SECRET,
            "key": "",
        }
    ]

SOCIALACCOUNT_LOGIN_ON_GET = False


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email (SendGrid SMTP by default when API key is present)
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if SENDGRID_API_KEY
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", SENDGRID_API_KEY)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@clawedin.local")

# Stripe
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_ID_FREE = os.environ.get("STRIPE_PRICE_ID_FREE", "")
STRIPE_PRICE_ID_PRO = os.environ.get("STRIPE_PRICE_ID_PRO", "")
STRIPE_PRICE_ID_BUSINESS = os.environ.get("STRIPE_PRICE_ID_BUSINESS", "")

# Solana wallet encryption (base64-encoded 32-byte key for Fernet)
SOLANA_WALLET_ENCRYPTION_KEY = os.environ.get("SOLANA_WALLET_ENCRYPTION_KEY", "")
SOLANA_RPC_URL = os.environ.get("SOLANA_RPC_URL", "https://api.mainnet-beta.solana.com")
BIRDEYE_API_KEY = os.environ.get("BIRDEYE_API_KEY") or os.environ.get("BIRDEY_API_KEY", "")

# Email verification
EMAIL_VERIFICATION_TTL_SECONDS = int(
    os.environ.get("EMAIL_VERIFICATION_TTL_SECONDS", str(60 * 60 * 24)),
)

BEARER_TOKEN_SHARED_SECRET = os.environ.get("BEARER_TOKEN_SHARED_SECRET", "")
BEARER_TOKEN_ISSUER = os.environ.get("BEARER_TOKEN_ISSUER", "").strip()
BEARER_TOKEN_ACCEPTED_ISSUERS = _split_env_list(
    os.environ.get("BEARER_TOKEN_ACCEPTED_ISSUERS", BEARER_TOKEN_ISSUER)
)

# Agent GUI ingress/proxy configuration
AGENT_GUI_PORT = int(os.environ.get("AGENT_GUI_PORT", "18789"))
AGENT_GUI_PROXY_PORT = int(os.environ.get("AGENT_GUI_PROXY_PORT", "18790"))
AGENT_GUI_PROXY_PORT = int(os.environ.get("AGENT_GUI_PROXY_PORT", "18790"))
AGENT_GUI_PATH_PREFIX = os.environ.get("AGENT_GUI_PATH_PREFIX", "/agents/gui")
AGENT_GUI_INGRESS_HOST = os.environ.get("AGENT_GUI_INGRESS_HOST", "")
AGENT_GUI_HOST_SUFFIX = os.environ.get("AGENT_GUI_HOST_SUFFIX", "")
AGENT_GUI_INGRESS_CLASS = os.environ.get("AGENT_GUI_INGRESS_CLASS", "")
AGENT_GUI_TLS_RESOLVER = os.environ.get("AGENT_GUI_TLS_RESOLVER", "")
AGENT_GUI_PROXY_BASE = os.environ.get("AGENT_GUI_PROXY_BASE", "")
AGENT_GUI_PROXY_TIMEOUT = int(os.environ.get("AGENT_GUI_PROXY_TIMEOUT", "30"))
AGENT_CLAWEDIN_CHANNEL_PORT = int(os.environ.get("AGENT_CLAWEDIN_CHANNEL_PORT", "31890"))
AGENT_CLAWEDIN_CHANNEL_REQUEST_PATH = os.environ.get("AGENT_CLAWEDIN_CHANNEL_REQUEST_PATH", "/v1/messages")
AGENT_CLAWEDIN_CHANNEL_TIMEOUT = int(os.environ.get("AGENT_CLAWEDIN_CHANNEL_TIMEOUT", "120"))

# Agent persistent storage
AGENT_OPENCLAW_PVC_NAME = os.environ.get("AGENT_OPENCLAW_PVC_NAME", "clawedin-vfs-pvc").strip()
AGENT_OPENCLAW_HOME = os.environ.get("AGENT_OPENCLAW_HOME", "/home/node/.openclaw").strip()
AGENT_NODE_HOSTNAME = os.environ.get("AGENT_NODE_HOSTNAME", "").strip()
AGENT_WORKER_ONLY = os.environ.get("AGENT_WORKER_ONLY", "true").strip().lower() == "true"
AGENT_OPENCLAW_UID = int(os.environ.get("AGENT_OPENCLAW_UID", "1000"))
AGENT_OPENCLAW_GID = int(os.environ.get("AGENT_OPENCLAW_GID", "1000"))
AGENT_OPENCLAW_PVC_MODE = os.environ.get("AGENT_OPENCLAW_PVC_MODE", "per_agent").strip().lower()
AGENT_OPENCLAW_PVC_STORAGE_CLASS = os.environ.get("AGENT_OPENCLAW_PVC_STORAGE_CLASS", "local-path").strip()
AGENT_OPENCLAW_PVC_SIZE = os.environ.get("AGENT_OPENCLAW_PVC_SIZE", "5Gi").strip()
AGENT_OPENCLAW_PVC_ACCESS_MODE = os.environ.get("AGENT_OPENCLAW_PVC_ACCESS_MODE", "ReadWriteOnce").strip()
AGENT_INTERNAL_HOST_ALIAS_ENABLED = os.environ.get("AGENT_INTERNAL_HOST_ALIAS_ENABLED", "true").strip().lower() == "true"
AGENT_INTERNAL_HOST = os.environ.get(
    "AGENT_INTERNAL_HOST",
    os.environ.get("AGENT_GUI_INGRESS_HOST", "openclawedin.com"),
).strip()
_agent_internal_hosts_env = os.environ.get("AGENT_INTERNAL_HOSTS", "").strip()
if _agent_internal_hosts_env:
    AGENT_INTERNAL_HOSTS = [
        value.strip()
        for value in _agent_internal_hosts_env.split(",")
        if value.strip()
    ]
else:
    AGENT_INTERNAL_HOSTS = []
    if AGENT_INTERNAL_HOST:
        AGENT_INTERNAL_HOSTS.append(AGENT_INTERNAL_HOST)
    if "jobs.openclawedin.com" not in AGENT_INTERNAL_HOSTS:
        AGENT_INTERNAL_HOSTS.append("jobs.openclawedin.com")
AGENT_INTERNAL_SERVICE_NAME = os.environ.get("AGENT_INTERNAL_SERVICE_NAME", "traefik").strip()
AGENT_INTERNAL_SERVICE_NAMESPACE = os.environ.get("AGENT_INTERNAL_SERVICE_NAMESPACE", "kube-system").strip()
AGENT_SHARED_VFS_ENABLED = os.environ.get("AGENT_SHARED_VFS_ENABLED", "true").strip().lower() == "true"
AGENT_SHARED_VFS_CLAIM_NAME = os.environ.get("AGENT_SHARED_VFS_CLAIM_NAME", "clawedin-vfs-pvc2").strip()
AGENT_SHARED_VFS_STORAGE_PATH = os.environ.get("AGENT_SHARED_VFS_STORAGE_PATH", "/mnt/vfs").strip()
AGENT_SHARED_VFS_MOUNT_PATH = os.environ.get(
    "AGENT_SHARED_VFS_MOUNT_PATH",
    "/home/node/.openclaw/workspace/clawedin-uploads",
).strip()
AGENT_DASHBOARD_ATTACHMENT_MAX_BYTES = int(
    os.environ.get("AGENT_DASHBOARD_ATTACHMENT_MAX_BYTES", str(25 * 1024 * 1024))
)
AGENT_BROWSER_SSRF_ALLOWED_HOSTNAMES = [
    value.strip()
    for value in os.environ.get(
        "AGENT_BROWSER_SSRF_ALLOWED_HOSTNAMES",
        ",".join(AGENT_INTERNAL_HOSTS),
    ).split(",")
    if value.strip()
]
AGENT_WEB_FETCH_SSRF_ALLOWED_HOSTNAMES = [
    value.strip()
    for value in os.environ.get(
        "AGENT_WEB_FETCH_SSRF_ALLOWED_HOSTNAMES",
        ",".join(AGENT_BROWSER_SSRF_ALLOWED_HOSTNAMES),
    ).split(",")
    if value.strip()
]
